### ISSUE TITLE
pyvicon on macOS

### ISSUE THREAD

**Issue by HosikChae** [MathGaron/pyvicon#2]
Hi, I am trying to install pyvicon on macOS, but building 'pyvicon_module' extension keep failing, and it seems it is because it cannot link to libViconDataStreamSDK_CPP.dylib.
Although I played with it for more than a week from giving linking options to Extension package in setup.py to manipulating @executable_path of the .dylib files, I could not install it.

**Comment by MathGaron** [comment]
Hi Hosik,
I did not try to install pyvicon on Mac OS yet, however as you said it might be a linking error with the dynamic librairies. First can you provide the compilation error?
Also, make sure that the dynamic libraries can be found in DYLD_LIBRARY_PATH.
If you happen to make things work, please give some feed back here to help others!

Thank you!

**Comment by HosikChae** [comment]
To leave a late update, I was able to resolve it by adding the SDK path to  `DYLD_LIBRARY_PATH` (10.15 Catalina). I heard that you should set up `DYLD_FALLBACK_LIBRARY_PATH` instead for further later macOS.

**Comment by steffensc** [comment]
Hey @HosikChae,

I ran into the same issue with the DYLD Path like you when I tried to compile the Vicon Datastream SDK on my MacBook M1 which has an ARM processor, but managed to fix it in the CMake of a new project I created. It's a module based on scikit-build which automatically does the compiling of the VDS SDK libs from the sources specific for each platform. 🎉

So for now you only have to run pip install pyvicon-datastream and you should be ready to use a python wrapper implementation for the Vicon Datastream SDK out of the box :)

https://pypi.org/project/pyvicon-datastream/
https://github.com/steffensc/pyvicon-datatstream-module
