### ISSUE TITLE
seg fault/terminate after running

### ISSUE THREAD

**Issue by jagauthier** [MathGaron/pyvicon#3]
I wrote  a simple Python program to grab coordinates of an object.

I'm doing a continual loop that looks like this:

```
    while True:
        vicon.get_frame()
        t=vicon.get_segment_global_translation(subject,root_seg_name)
        if t is None:
            continue
        x=t[0]/1000;
        y=t[1]/1000;
        z=t[2]/1000;
        print("X: {0:.6f} Y: {0:.6f} Z: {0:.6f}".format(x,y,z))
        time.sleep(.01)
```

After running for a period of time the call to get_frame fails with either a segmentation fault or 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Unfortunately, it appears to be happening in pyvicon.cpp at this line:
out = client->GetFrame();

I suspect this is internal to the Vicon SDK, But I don't know.

UPDATE:
Fixed by changing the client to Pull from PreFetch

**Comment by MathGaron** [comment]
Great that it works, thanks for updating!
